export enum RecordType {
    FINANCE_RECORD = "FINANCE_RECORD",
    FINANCE_SUMMARY_RECORD = "FINANCE_SUMMARY_RECORD",
    FINANCE_ALL_SUMMARY_RECORD = "FINANCE_ALL_SUMMARY_RECORD",
};

export enum InvestmentType {
    MUTUAL_FUND = "MUTUAL_FUND",
    BANKING = "BANKING",
    FIXED_DEPOSIT = "FIXED_DEPOSIT",
    TAX_SAVER = "TAX_SAVER",
};