create:
  handler: src/handlers/crud_operations/create.handler
  events:
    - http:
        path: create
        method: post
        cors: true
        private: true

read:
  handler: src/handlers/crud_operations/read.handler
  events:
    - http:
        path: read
        method: post
        cors: true
        private: true
update:
  handler: src/handlers/crud_operations/update.handler
  events:
    - http:
        path: update
        method: put
        cors: true
        private: true

delete:
  handler: src/handlers/crud_operations/delete.handler
  events:
    - http:
        path: delete
        method: delete
        cors: true
        private: true
