handler: ./src/handlers/llm_bot/index.handler
runtime: python3.11
events:
  - http:
      path: bot
      method: post
      cors: true
      private: true

environment:
  API_URL: https://dk9kf4326l.execute-api.us-east-1.amazonaws.com/dev/
  API_KEY: ${self:provider.environment.API_KEY}
  AI_ACCESS_KEY_ID: ${self:provider.environment.AI_ACCESS_KEY_ID}
  AI_SECRET_ACCESS_KEY: ${self:provider.environment.AI_SECRET_ACCESS_KEY}
  AI_AWS_REGION: us-east-1