handler: src/handlers/llm_bot/index.handler
runtime: python3.12
events:
  - http:
      path: bot
      method: post
      cors: true
      private: true

environment:
  API_URL: https://dk9kf4326l.execute-api.us-east-1.amazonaws.com/dev/
  API_KEY: ${env:API_KEY}
  AWS_ACCESS_KEY_ID: ${env:AI_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${env:AI_SECRET_ACCESS_KEY}
  AWS_REGION: ${self:provider.region}